#!/bin/sh
# GENERATED by bin/generate-viewer from apps/thunderbird.conf + templates/ -- DO NOT EDIT.
# xpra --start-child: set up a passwordless gnome-keyring (Signal stores its DB
# encryption key via libsecret/safeStorage, same pattern as 1Password's 2FA token)
# BEFORE launching Signal. Must run inside dbus-run-session (the entrypoint does that).
set -u
: "${HOME:=/home/thunderbird}"
export HOME

KR="$HOME/.thunderbird/.keyrings"
mkdir -p "$KR" "$HOME/.local/share"
ln -sfn "$KR" "$HOME/.local/share/keyrings" 2>/dev/null || {
  rm -rf "$HOME/.local/share/keyrings"
  ln -sfn "$KR" "$HOME/.local/share/keyrings"
}
if [ ! -e "$KR/default" ]; then
  printf '[keyring]\ndisplay-name=login\nctime=0\nmtime=0\nlock-on-idle=false\nlock-after=false\n' > "$KR/login.keyring"
  chmod 600 "$KR/login.keyring"
  printf login > "$KR/default"
fi
eval "$(printf '' | gnome-keyring-daemon --unlock --components=secrets 2>/dev/null)"

# Launch the app with its manifest-configured flags. (Electron apps typically need
# --no-sandbox here -- their setuid sandbox doesn't work in this container; GTK apps
# usually need none. Set them per-app via APP_FLAGS.)
# Live menu bridge: bring up the AT-SPI a11y bus BEFORE the app registers (GTK menu
# bars need atk-bridge at startup), then start the menu daemon. It polls for the app's
# menu bar and serves /run/user/1000/porthole-menu.sock. Verified: Thunderbird exposes File/Edit/
# View/Go/Message/Tools/Help this way even though its menu bar is hidden in the UI.
export GTK_MODULES=atk-bridge
/usr/libexec/at-spi-bus-launcher --launch-immediately >/tmp/atspi-bus.log 2>&1 &
sleep 3
dbus-send --session --type=method_call --dest=org.a11y.Bus /org/a11y/bus \
  org.freedesktop.DBus.Properties.Set string:org.a11y.Status string:IsEnabled \
  variant:boolean:true 2>/dev/null || true
python3 /usr/local/bin/porthole-menu-daemon.py /run/user/1000/porthole-menu.sock \
  >/tmp/porthole-menu-daemon.log 2>&1 &
exec thunderbird 
