#!/bin/sh
# GENERATED by bin/generate-viewer from apps/clion.conf + templates/ -- DO NOT EDIT.
# Entrypoint: ONE Linux CLion instance served by xpra on :100 (for the Porthole native client),
# on the persistent data volume. xpra provides its own Xvfb; no in-container WM. Optional
# bridges (printing/CUPS, CAP_SYS_PTRACE, audio, ...) are included below per the manifest.
set -u
# xpra binds a Unix-domain socket (not TCP). It lives in the app user's runtime dir
# (created + chowned below); the launcher's socat bridge -- running as root via
# `docker exec` -- connects to it by path. No TCP port, nothing network-exposed.
: "${XPRA_SOCKET:=/run/user/1000/porthole-xpra.sock}"
: "${XPRA_DISPLAY:=:100}"

# Data volume (clion-gui-data) mounts at /home/clion/.config/JetBrains, arrives root-owned.
mkdir -p /home/clion/.config/JetBrains /run/user/1000
chown -R clion:clion /home/clion/.config /run/user/1000
chmod 700 /run/user/1000

# --encodings matches the Porthole client (rgb is alpha-preserving; no jpeg black
# margins). open-url + file-transfer are generic bridges (links, attachments).
exec env HOME=/home/clion XDG_RUNTIME_DIR=/run/user/1000 \
  setpriv --reuid clion --regid clion --init-groups \
    -- xpra start "$XPRA_DISPLAY" --daemon=no --bind="$XPRA_SOCKET" \
       --encodings=rgb \
       --open-url=yes --file-transfer=yes \
       --notifications=yes --pulseaudio=no --mdns=no \
       --start-child="dbus-run-session -- /usr/local/bin/clion-child.sh" \
       --exit-with-children=yes
